# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@1
  displayName: Restore
  inputs:
    command: restore
    
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    arguments: '--configuration Release'
    
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
  # Pack a NuGet package to a test directory
- task: DotNetCoreCLI@2
  displayName: 'Publish CLI Tool'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: SiteCoreFixConsole/*.csproj
    arguments: '-o CLITool --configuration Release --framework netcoreapp2.2'
    zipAfterPublish: true
    modifyOutputPath: true
    
- task: DotNetCoreCLI@2
  displayName: 'Publish GUI Tool'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: SiteCoreFixup/*.csproj
    arguments: '-o GUITool --configuration Release --framework netcoreapp3.1'
    zipAfterPublish: true
    modifyOutputPath: true
    